### PR TITLE
chore: create scorecard.yml

### LINKED ISSUE #675: Enable OpenSSF Scorecard
OpenSSF Scorecard  helps open source projects to improve their security practices and help consumers evaluate the safety of their dependencies.

### PR DESCRIPTION
**Pull request by rvema**
Enabling OpenSSF Scorecard  would help git-proxy project improve its security practices and help consumers evaluate the safety of their dependencies.

Fixes #675

### CODE REVIEW

**Comment by JamieSlome** [comment]
@rvema - thank you for your PR 👍 ❤️ A great idea to get this added to the project.

Are you able to take a look at the FINOS EasyCLA? You'll need to sign this before your PR can be merged.

**Comment by JamieSlome** [comment]
@rvema - shall we also include a badge in the `README.md` with the score?

**Comment by rvema** [comment]
Sure , let me add the badge and sign the cla

**Comment by rvema** [comment]
added the badge but the score will not be there and will autofix once it runs at least 1 time on push. For now it will be run on every push to main branch and on a schedule

**Review by JamieSlome — APPROVED** [review]
LGTM! 🍰

**Comment by JamieSlome** [comment]
Thank you for the contribution @rvema ❤️ 

Hopefully the first of many!

**Pull request merged**
