### PR TITLE
Add finos (incubating) badge in README

### PR DESCRIPTION
**Pull request by finos-admin**

### CODE REVIEW

**Comment by JamieSlome** [comment]
@maoo - what is the purpose of this?

**Comment by maoo** [comment]
> @maoo - what is the purpose of this?

This is to notify consumers about the maturity of the project; it's a standard practice at FINOS, and every software project must (it's a mandatory component of our [software project blueprint](https://github.com/finos/software-project-blueprint/)) expose one of 3 stages: Incubating, Active or Archived. You can read more on https://community.finos.org/docs/governance/Software-Projects/project-lifecycle

**Comment by JamieSlome** [comment]
What does the badge link to, or is it purely for display purposes? I get to an Atlassian login page.

**Comment by maoo** [comment]
> What does the badge link to, or is it purely for display purposes? I get to an Atlassian login page.

Ouch, sorry about that, by bad. Fixed the link, should point to https://community.finos.org/docs/governance/Software-Projects/stages/incubating , which explains what it means to be a FINOS Incubating project

**Review by JamieSlome — APPROVED** [review]

**Pull request merged**
