### PR TITLE
Implement FINOS Security Scanning

### LINKED ISSUE #116: Implement FINOS Security Scanning
_Originally posted by @maoo in https://github.com/finos/git-proxy/pull/115#pullrequestreview-1498898957_

### PR DESCRIPTION
**Pull request by JamieSlome**
Closes #116

### CODE REVIEW

**Comment by TheJuanAndOnly99** [comment]
Hi @JamieSlome. The CVE Scanning for Node.js action is working properly. It is reporting 5 CVEs. 

[2 of them](https://github.com/finos/git-proxy/actions/runs/5380615087/jobs/9763582716?pr=117#step:5:249) are related to the [passport package](https://www.npmjs.com/package/passport) and can be solved by installing the latest version. Though they are not "critical" and could potentially be added to the ignore file if needed.

[Another CVE ](https://github.com/finos/git-proxy/actions/runs/5380615087/jobs/9763582716?pr=117#step:5:222)is related to the [nedb package](https://www.npmjs.com/package/nedb). This one may be a bit trickier to deal with as it seems to be an old library that has not been updated in a while. It is also [causing a "critical" CVE](https://github.com/finos/git-proxy/actions/runs/5380615087/jobs/9763582716?pr=117#step:5:358) as it relies on a vulnerable version of the underscore package. Is this package critical to git-proxy?

[The last CVE is related to the semver package](https://github.com/finos/git-proxy/actions/runs/5380615087/jobs/9763582716?pr=117#step:5:316) which is being used by many libraries that need to be updated. In order to manage this more easily I recommend we install the [Renovate Github app](https://docs.renovatebot.com/). It will monitor the repo and recommend via PR version upgrades as necessary. I've installed it on [my fork of the git-proxy repo ](https://github.com/TheJuanAndOnly99/git-proxy/pull/1) and it is recommending 40 version upgrades many of which are subject to the semver CVE. With your okay I will go ahead and install the app on the FINOS git-proxy repository so that you can start getting these PRs. Let me know.

I

**Comment by JamieSlome** [comment]
Hey @TheJuanAndOnly99 👋 

Let's get Renovate installed, I generally prefer it over Dependabot. We can start reviewing the recommendations as they come in.

In any case, I believe that Dependabot is [notifying of the same vulnerabilities](https://github.com/finos/git-proxy/security/dependabot).

It may take migration to some new dependencies to resolve some of these vulnerabilities as some of them look transitive. Let's see how we go with Renovate now 👍

**Comment by TheJuanAndOnly99** [comment]
@JamieSlome Yes I think so. I've just enabled Renovate, you should start getting some PRs from the bot!

**Comment by JamieSlome** [comment]
@TheJuanAndOnly99, all reviewed and merged 👍 

@grovesy - any easy way for us to remove `nedb`?

We can look to white-list for the time-being and follow-up after.

**Comment by maoo** [comment]
I'd suggest to avoid releasing anything with known critical vulnerabilities.

Looks like nedb was forked due to lack of maintenance, see https://www.npmjs.com/package/@seald-io/nedb

Not sure if there are other alternatives though.

@JamieSlome - could you give this a try?

**Comment by JamieSlome** [comment]
> I'd suggest to avoid releasing anything with known critical vulnerabilities.
> 
> Looks like nedb was forked due to lack of maintenance, see https://www.npmjs.com/package/@seald-io/nedb
> 
> Not sure if there are other alternatives though.
> 
> @JamieSlome - could you give this a try?

On my way! 🍰  See #161

**Comment by JamieSlome** [comment]
@maoo - done 🎉 

See #162 for your review...

**Comment by TheJuanAndOnly99** [comment]
Hi @JamieSlome I just sent a PR https://github.com/finos/git-proxy/pull/163 that contains the updates I reverted to make the build work again. It seems it was related to updating to react 18. Which should be done if possible but would probably require some more effort. Though it seems it does not present any CVEs at the moment.

**Pull request merged**
