### PR TITLE
refactor: code clone component

### LINKED ISSUE #630: Add code clone component to repository page ⬇️
**Is your feature request related to a problem? Please describe.**

Without pagination and search (until #606), it can be painful to locate the clone command/URL on the Repositories page.

**Describe the solution you'd like**

Create a component for the widget (<Clone />) and add component to the Repository page.

Screenshot 2024-06-27 at 11 37 30

**Additional context**

The code to move into a new `<Clone />` component [can be found in](https://github.com/finos/git-proxy/blob/5401677e0b57583c0e50ab66d155066c77f7a85f/src/ui/views/RepoList/Components/RepoOverview.jsx#L688) `RepoOverview.js` from line `688` to `778`.

### PR DESCRIPTION
**Pull request by tt-gideonaryeetey**
Closes #630

### CODE REVIEW

**Comment by JamieSlome** [comment]
@tt-gideonaryeetey - thanks for the pull request 🎉 

Are we able to include a Cypress test to ensure the stability of the new component moving forward?

**Comment by tt-gideonaryeetey** [comment]
> @tt-gideonaryeetey - thanks for the pull request 🎉
> 
> Are we able to include a Cypress test to ensure the stability of the new component moving forward?

Yes, we can definitely include a Cypress test. I'll start working on it

**Comment by JamieSlome** [comment]
@tt-gideonaryeetey - amazing, thank you 👍

**Review by JamieSlome — APPROVED** [review]
LGTM! 🍰

**Pull request merged**
