### PR TITLE
docs: replaced "Git Proxy" with "GitProxy"

### LINKED ISSUE #613: Find and replace all usage of "Git Proxy" with "GitProxy"
Pretty self explanatory. Helps with find-ability and search-ability.

Search: `git proxy` typically provides results about the `git http.proxy` configuration

Search `gitproxy` 🎉 

This will help prevent overlap between our project and the search space for the git CLI. This is a super duper easy issue so definitely worth picking up and submitting a PR for 👍 
```[tasklist]
### Tasks
- [ ] Find and replace usage in `website` folder
- [ ] Find and replace usage in `README.md`
```

### PR DESCRIPTION
**Pull request by DanielVenable**
Closes #613

### CODE REVIEW

**Comment by JamieSlome** [comment]
@DanielVenable - are you able to sign the CLA using EasyCLA? Let me know if you have any questions.

**Comment by DanielVenable** [comment]
> @DanielVenable - are you able to sign the CLA using EasyCLA? Let me know if you have any questions.

I signed it

**Comment by JamieSlome** [comment]
Are you able to resolve the merge conflict? 👍 Thank you!

**Review by JamieSlome — APPROVED** [review]
LGTM! 🍰

**Comment by JamieSlome** [comment]
@DanielVenable - thank you very much for your contribution ❤️ If you've enjoyed working on the project, let me know if there is another issue you'd like to tackle and happy to walkthrough and support.

P.S. a star is always appreciated ⭐

**Pull request merged**
