### PR TITLE
Mongo

### PR DESCRIPTION
**Pull request by grovesy**
Mongo integration

### CODE REVIEW

**Comment by maoo** [comment]
@grovesy - FYI - working on the license failure, see https://github.com/finos/git-proxy/commit/87d1cb5444295b2c34b3c858c41cf82a786190b6 . Will keep you posted.

**Comment by grovesy** [comment]
Great thanks - let me know!

**Comment by maoo** [comment]
> Great thanks - let me know!

Should be fixed by https://github.com/finos/git-proxy/pull/40

Could you please check all package.json `dependencies` to see if they can "survive" as `devDependencies`?

Thanks!

**Comment by grovesy** [comment]
yeh checked them - all are valid for runtime

I'll see if we can drop a few of them if problems?

**Pull request merged**
