### PR TITLE
fix: ensure npm publish includes build directory

### PR DESCRIPTION
**Pull request by tt-gideonaryeetey**

### CODE REVIEW

**Comment by JamieSlome** [comment]
@tt-gideonaryeetey - have you signed the EasyCLA? 🤔

**Comment by tt-gideonaryeetey** [comment]
> @tt-gideonaryeetey - have you signed the EasyCLA? 🤔

Yes

**Comment by maoo** [comment]
> > @tt-gideonaryeetey - have you signed the EasyCLA? 🤔
> 
> Yes

I can check what is going on, but I'd need to know if you signed an Individual or Corporate CLA ; if the latter, EasyCLA requires a double confirmation for affiliation: one comes from the contributor, the other from the CLA Manager from your employer; I need to know who is your employer in order to validate which of the 2 confirmations is missing.

**Comment by tt-gideonaryeetey** [comment]
> > > @tt-gideonaryeetey - have you signed the EasyCLA? 🤔
> > 
> > 
> > Yes
> 
> I can check what is going on, but I'd need to know if you signed an Individual or Corporate CLA ; if the latter, EasyCLA requires a double confirmation for affiliation: one comes from the contributor, the other from the CLA Manager from your employer; I need to know who is your employer in order to validate which of the 2 confirmations is missing.

I signed as Corporate CLA. My employer is turntabl.

**Comment by maoo** [comment]
> > > > @tt-gideonaryeetey - have you signed the EasyCLA? 🤔
> > > 
> > > 
> > > Yes
> > 
> > 
> > I can check what is going on, but I'd need to know if you signed an Individual or Corporate CLA ; if the latter, EasyCLA requires a double confirmation for affiliation: one comes from the contributor, the other from the CLA Manager from your employer; I need to know who is your employer in order to validate which of the 2 confirmations is missing.
> 
> I signed as Corporate CLA. My employer is turntabl.

I see that you're approved using your @turntabl.io email address; this means that a) your [git client must be configured accordingly](https://linuxize.com/post/how-to-configure-git-username-and-email/) and b) your Github account must list that email addresses under https://github.com/settings/emails


I checked (a) via https://api.github.com/repos/finos/git-proxy/commits/d614e703215111095f26da7c7804582283858138 , so we're good. Unless (b) is what is missing, then the issue is that the affiliation confirmation from you (the contributor) is missing, and you need to access https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/13399143/256513079/578/#/?version=2 in order to complete the process.

Hope this helps!

**Comment by tt-gideonaryeetey** [comment]
> > > > > @tt-gideonaryeetey - have you signed the EasyCLA? 🤔
> > > > 
> > > > 
> > > > Yes
> > > 
> > > 
> > > I can check what is going on, but I'd need to know if you signed an Individual or Corporate CLA ; if the latter, EasyCLA requires a double confirmation for affiliation: one comes from the contributor, the other from the CLA Manager from your employer; I need to know who is your employer in order to validate which of the 2 confirmations is missing.
> > 
> > 
> > I signed as Corporate CLA. My employer is turntabl.
> 
> I see that you're approved using your @turntabl.io email address; this means that a) your [git client must be configured accordingly](https://linuxize.com/post/how-to-configure-git-username-and-email/) and b) your Github account must list that email addresses under https://github.com/settings/emails
> 
> I checked (a) via https://api.github.com/repos/finos/git-proxy/commits/d614e703215111095f26da7c7804582283858138 , so we're good. Unless (b) is what is missing, then the issue is that the affiliation confirmation from you (the contributor) is missing, and you need to access https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/13399143/256513079/578/#/?version=2 in order to complete the process.
> 
> Hope this helps!

Thank you for the suggestions. I went through all the steps again to ensure I didn't miss anything. I pushed an update, and it seems to have passed the CLA check.

**Review by JamieSlome — APPROVED** [review]
LGTM! 🍰

**Pull request merged**
