### PR TITLE
Revamp the `README.md` with a lick of paint 🎨 

### LINKED ISSUE #177: Revamp the `README.md` with a lick of paint 🎨
The `README.md` needs a lick of paint to reflect some of the latest improvements and changes.

```[tasklist]
### Tasks
- [ ] Add more [badges](https://shields.io) for license, forks, stars and npm package
- [ ] Revamp the `README.md` using the [following format](https://github.com/othneildrew/Best-README-Template)
- [ ] Provide simple installation and get-started instructions
```

### PR DESCRIPTION
**Pull request by JamieSlome**
Closes #177

### CODE REVIEW

**Comment by JamieSlome** [comment]
@maoo - more of an approach preference, but should we remove the usage section of this for now, merge the PR, and reconcile the invocation of the library, as it still needs work? We can then look to update the usage section after?

**Comment by maoo** [comment]
Sounds good, especially considering that for the `Usage` part we may need a dedicated MD file; let's iterate on this later. TY!

**Comment by JamieSlome** [comment]
@maoo - ready for your review 👍 You might need to disable the `Linting` merge requirement for the time being.

**Review by maoo — COMMENTED** [review]
Looks really nice, great work @JamieSlome !

The only thing that I would change is `Otherwise, reach out to [opensource@citi.com](mailto:opensource@citi.com).` at the bottom of the README. I'd suggest to keep communication public and hosted on GitHub, as much as possible.

If you need an email address that can relay messages, you can mention `help@finos.org` .

WDYT?

**Comment by JamieSlome** [comment]
@maoo - done ✅

**Review by maoo — APPROVED** [review]
LGTM!

**Pull request merged**
