### PR TITLE
Support `npx` usage and fix default configuration loading

### PR DESCRIPTION
**Pull request by JamieSlome**
In support of #183

### CODE REVIEW

**Comment by JamieSlome** [comment]
@TheJuanAndOnly99 - looks like we can remove the `push` trigger for the CVE scanning. Thoughts?

**Comment by TheJuanAndOnly99** [comment]
@JamieSlome Yes that would be fine. I think if we do that we should also set a branch protection rule on the `main` branch to require a pull request before merging. What do you think?

**Comment by JamieSlome** [comment]
@TheJuanAndOnly99 - yes, perfect! I don't have full access to the repository's administrative settings. Is this something we can also arrange?

**Comment by TheJuanAndOnly99** [comment]
@JamieSlome I've just sent a PR https://github.com/finos/git-proxy/pull/189 with the update to the action. And I have set branch protection on the `main` branch to require a PR before merging. 

As far as admin rights go. FINOS policy is to not grant permanent admin rights to anyone (only the finos-admin user has admin privileges). But if you need temporary admin access to set something up inside the repo we can arrange that if you email help@finos.org.

**Comment by JamieSlome** [comment]
@TheJuanAndOnly99 - merged, thank you 🎉 

No worries with regards to the permissions!

**Comment by JamieSlome** [comment]
Closing as discussed with @coopernetes in the fortnightly catch-up yesterday.

**Pull request closed without merging**
