### PR TITLE
Add ESLINT and Prettier with autosave

### LINKED ISSUE #193: Implement best ESLINT and Prettier combo with auto save 💪
Currently, the ESLINT and Prettier setup is not sufficient for enforcing code cleanliness or readable files.

```[tasklist]
### Tasks
- [ ] Install the most relevant ESLINT and Prettier modules for the project
- [ ] Create a set of scripts in the `package.json` to mass lint and prettify
- [ ] Ensure ESLINT and Prettier warnings are visible in IDE
- [ ] Auto linting and pretty on save
- [ ] Bonus points 🏆 - create a GitHub Action to validate all files are linted and pretty
```

### PR DESCRIPTION
**Pull request by vaibssingh**
Closes #193 

Changelog:

- [x]  Install the most relevant ESLINT and Prettier modules for the project
- [x] Create a set of scripts in the package.json to mass lint and prettify
- [x] Ensure ESLINT and Prettier warnings are visible in IDE
- [x] Auto linting and pretty on save (works in VS Code)
- [x] Bonus points 🏆 - create a GitHub Action to validate all files are linted and pretty

Notes:
1. Some of the rules in ```eslintrc``` have been disabled/modified to avoid conflicting rules between eslint & prettier and to follow the existing standards of the repo.
2. The quotes rule has been disabled in some of the files due to it creating problems with existing code and producing more eslint issues.
3. I observed that while auto lint works on explicitly saving file using Cmd+S, it doesn't work with autosave enabled in VSC. So you have to do Cmd+S manually for auto lint to work. It is the expected behaviour in VSC as discussed in the thread below so it should not be considered an issue:
https://github.com/microsoft/vscode/issues/121155

### CODE REVIEW

**Comment by vaibssingh** [comment]
Hey @JamieSlome! Sorry about the delay with this PR. Didn't find time from daily work to close this sooner.
Have added all the points as mentioned in your task list. The GitHub action to verify the linting workflow works as well. Let me know if there is anything else that's needed to be done on this 😃

**Comment by JamieSlome** [comment]
@TheJuanAndOnly99 - can we make the linting check a requirement for PRs prior to merging in the repository settings?

**Comment by maoo** [comment]
This is how the `main` branch protection looks like now. Is that ok?

Screenshot 2023-07-31 at 19 28 34

**Comment by JamieSlome** [comment]
@vaibssingh, my last question is, how will the results be reported to the developer? In the GitHub Actions console?

**Comment by JamieSlome** [comment]
@maoo - sorry to be a pain, but can we disable the check requirement for the time being? It seems to be preventing the merging of all other PRs, and I still need to review the contents of this PR 🤗

**Comment by vaibssingh** [comment]
> @vaibssingh, my last question is, how will the results be reported to the developer? In the GitHub Actions console?

@JamieSlome Yep. It would look something like this
https://github.com/finos/git-proxy/actions/runs/5709151849/job/15467588676

**Comment by TheJuanAndOnly99** [comment]
@JamieSlome I've removed the linting check for now. Let me know when you're ready and I can enable it again.

**Comment by JamieSlome** [comment]
Thank you, @TheJuanAndOnly99 😄

**Comment by JamieSlome** [comment]
@vaibssingh - looks like there is still a merge conflict for some reason. Once that is addressed, we can merge! 🎉

**Comment by JamieSlome** [comment]
@vaibssingh - do you want to give the latest merge conflict a go and see if that resolves the CVE breakage? 👍 Thank you for your patience! 🍰

**Comment by vaibssingh** [comment]
Hey @JamieSlome , I have tried multiple times for this to work but I am not able to get it resolved. The material-ui requests ```@types/react@17.0.63``` but during npm install using node v16.19 it installs ```@types/react@18.2.19```. Since we have ```npm ci``` instead of ```npm i``` for this CVE workflow, on encountering this conflict it stops the pipeline which causes it to fail. Do you have any idea how we can fix it?

**Review by JamieSlome — APPROVED** [review]
LGTM! 🍰

**Pull request merged**
