### PR TITLE
Re-introduce CSRF protection with Lusca ❤️ 

### LINKED ISSUE #492: Error: CSRF token missing 🐛
**Describe the bug**

When logging in via the UI, the following error is received:

```bash
Error: CSRF token missing
 at checkCsrf (.../git-proxy/node_modules/lusca/lib/csrf.js:169:18)
```

**To Reproduce**
1. Checkout to the `reconcile` branch
2. Go to `/login` via the UI
3. Enter `admin` & `admin` for username and password credentials
4. Submit login form
5. View locally running logs on dev machine

**Additional context**

CSRF added in PR: https://github.com/finos/git-proxy/pull/462

### PR DESCRIPTION
**Pull request by JamieSlome**
Closes #492 

@vaibssingh - the fix was to move the CSRF exposure lower into `app.use()` call chain 👍

### CODE REVIEW

**Comment by JamieSlome** [comment]
@maoo - are we able to remove the Socket plugin from the project? It seems to be introducing a lot of noise 👍

**Comment by maoo** [comment]
> @maoo - are we able to remove the Socket plugin from the project? It seems to be introducing a lot of noise 👍

Sure! You want the entire app to be removed, or just one of the branch validation checks?

**Comment by JamieSlome** [comment]
@maoo - entire app for now 👍

**Comment by maoo** [comment]
> @maoo - entire app for now 👍

done!

**Pull request closed without merging**
