### PR TITLE
Design quick-start installation, usage and happy path documentation

### LINKED ISSUE #296: Design quick-start installation, usage and happy path documentation
To support #287 and the release of [v1.1.0](https://github.com/finos/git-proxy/releases/tag/v1.1.0), a simple and easy-to-follow set of instructions need to be included in the `README.md` and `docs`.

```[tasklist]
### Tasks
- [x] Add a clear documentation badge at the top of the `README.md`
- [x] Add simple instructions for installing the library and using it in a local environment
- [x] Include simple instructions for reproducing a happy path of a custom authorized repository
- [x] Explain how to store git credentials on the client to prevent excessive manual authentication per push
- [x] Add the above steps to the documentation website
```

### PR DESCRIPTION
**Pull request by JamieSlome**
Closes #296

### CODE REVIEW

**Review by maoo — APPROVED** [review]
LGTM!

**Comment by JamieSlome** [comment]
@coopernetes @maoo - would be good to get your thoughts on the changes to the documentation 👍

**Comment by JamieSlome** [comment]
@maoo - are we able to get previews of changes to the website deploying in pull requests? Also, should we move the website to its own branch? Not sure it makes much sense to distribute the library with the `website` in `node_modules`.

**Comment by maoo** [comment]
> @maoo - are we able to get previews of changes to the website deploying in pull requests? 

It should be already in place TBH, though I checked Netlify logs and there was no build since August; I've re-linked the repo, hopefully this will solve the issue. Could you please try to make another push on the `296-design-quick-start-installation-usage-and-happy-path-documentation` branch?

> Also, should we move the website to its own branch? Not sure it makes much sense to distribute the library with the `website` in `node_modules`.

I'd suggest add `docs` and `website` into `.npmignore`, and keep one repo for code and docs, as it would make it easier to manage.

**Pull request merged**
