### PR TITLE
Ui2 and authorisation

### PR DESCRIPTION
**Pull request by pGrovesy**

### CODE REVIEW

**Comment by maoo** [comment]
`npm run test` seems to be failing, see https://github.com/pGrovesy/git-proxy/blob/master/.github/workflows/nodejs.yml#L34

Feel free to merge and fix it later (or disable the tests for now).

**Comment by grovesy** [comment]
Yes seen it – fixing ☺

**Comment by grovesy** [comment]
@maoo 

can you apply the changes to this branch - there is only one package.json now

**Comment by grovesy** [comment]
@maoo 
We also need the license validation updated

**Comment by maoo** [comment]
> @maoo
> We also need the license validation updated

Did you do it? I see that the current version on this branch is fine. I think we're ready to merge; if you're ok too, please hit the button!

**Comment by grovesy** [comment]
done! sorry got caught up today

**Pull request merged**
